// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Test.Models.Context;

namespace Test.Migrations.MySqlMigrations
{
    [DbContext(typeof(dbTestMySqlContext))]
    [Migration("20220413164810_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Test.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("EditorialId")
                        .HasColumnType("int");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EditorialId" }, "EditorialId");

                    b.ToTable("book");
                });

            modelBuilder.Entity("Test.Models.Editorial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit(1)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("editorial");
                });

            modelBuilder.Entity("Test.Models.Book", b =>
                {
                    b.HasOne("Test.Models.Editorial", "Editorial")
                        .WithMany("Books")
                        .HasForeignKey("EditorialId")
                        .HasConstraintName("book_ibfk_1");

                    b.Navigation("Editorial");
                });

            modelBuilder.Entity("Test.Models.Editorial", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
